# Generated by Django 6.0.4 on 2026-05-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_is_voided_sale_void_reason_sale_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
