# Generated by Django 6.0.4 on 2026-05-12 20:41

from django.db import migrations


def backfill_unit_cost(apps, schema_editor):
    SaleItem = apps.get_model('sales', 'SaleItem')
    # Use F expression to set unit_cost_at_sale to product.cost_price if possible,
    # but we have to do it with a loop since product cost might have changed?
    # Wait, the best we can do is the current product cost price.
    for item in SaleItem.objects.select_related('product').all():
        if item.unit_cost_at_sale is None:
            item.unit_cost_at_sale = item.product.cost_price
            item.save(update_fields=['unit_cost_at_sale'])

def reverse_backfill(apps, schema_editor):
    SaleItem = apps.get_model('sales', 'SaleItem')
    SaleItem.objects.update(unit_cost_at_sale=None)

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_unit_cost_at_sale'),
    ]

    operations = [
        migrations.RunPython(backfill_unit_cost, reverse_backfill),
    ]
