# Generated by Django 6.0.4 on 2026-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('IN', 'Goods Arrived (IN)'), ('OUT', 'Goods Sold (OUT)'), ('ADJUST', 'Stock Adjusted'), ('CREATE', 'Added New'), ('UPDATE', 'Modified / Updated'), ('VOID', 'Cancelled / Voided'), ('LOGIN', 'Logged In')], max_length=20),
        ),
    ]
